export { Anasayfa } from "./Anasayfa";
export { Test } from "./Test";
export { Test2 } from "./Test2";
export { Login } from "./Login";
export { Error } from "./Error";
export { Hizmetlerimiz } from "./Hizmetlerimiz";
export { BultenMain } from "./BultenMain";
export { BultenTek } from "./BultenTek";
export { Dashboard } from "./Dashboard";
